set -g mouse on
set -g renumber-windows on
set -g history-limit 50000

set -sg escape-time 10
setw -g mode-keys vi

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

set -g status-style bg=colour235,fg=colour250
set -g window-status-current-style bg=colour39,fg=black,bold
set -g window-status-style bg=colour235,fg=colour244
set -g status-left-style fg=colour81,bg=colour235
set -g status-right-style fg=colour245,bg=colour235

set -s set-clipboard on
set -g default-terminal "tmux-256color"
set -g terminal-features[3] '*:clipboard'
set -g terminal-features[4] 'xterm-256color:RGB'
